// Issue #2 — Wednesday, September 23, 2026 (regular)
export const issue2 = {
  id: "issue-2",
  issueNumber: 2,
  dateline: "Wednesday · September 23, 2026",
  kind: "regular",
  deck: "The new before the news.",
  readingLevel: "Upper high school · approx. Grade 10",
  nextLine: "Next edition arrives Friday.",
  ai: [
    {
      id: "ai-safety-pact",
      kicker: "01 / Governance",
      title: "The labs build a joint rulebook",
      body: "OpenAI, Anthropic, and Google DeepMind confirmed this week that they have spent several weeks coordinating on AI safety — jointly unveiling cyber-focused safeguards and access programs, a sharp break from their usual public competition. OpenAI’s policy chief Chris Lehane said in Washington the talks include a possible industry standards body, and Sam Altman committed OpenAI to embedding independent external evaluators in its own processes. Meanwhile the UK parliament’s Business, Innovation, Science and Trade Committee invited all three labs — plus Meta — to give evidence at an AI security hearing on October 13, where lawmakers will press on mandatory pre-release testing and whether development should slow for safety. Separately, Google DeepMind’s Demis Hassabis floated an oversight body modeled on FINRA, the US finance industry’s self-regulator: funded by AI companies, run by independent experts.",
      why: "Rivals writing rules together is either the start of real governance or a cartel in a trench coat — and October 13 is when we find out which.",
      prediction: "Expect at least one lab to publish an independent-evaluator framework before the October 13 hearing — the hearing turns coordination talk into legislative language.",
      confidence: "medium",
    },
    {
      id: "ai-launch-day",
      kicker: "02 / Models",
      title: "Launch-day chess",
      body: "OpenAI released two new models, GPT-6 Sol for complex work like coding and GPT-6 Luna for everyday tasks, roughly 90 minutes after Anthropic unveiled Claude Opus 5.5 — the first of its new Claude 5.5 family. Anthropic paired its launch with price cuts and zero-data-retention options, betting enterprises pick affordable, safer models over raw frontier power. Both launches landed within hours of each other, and neither lab pretended the timing was a coincidence.",
      why: "Model releases are now scheduled like product drops — the 90-minute gap was the message.",
      prediction: "Sub-two-hour spoiling launches become routine; the price war keeps cutting enterprise AI costs through year-end.",
      confidence: "medium",
    },
    {
      id: "ai-rubin",
      kicker: "03 / Compute",
      title: "Rubin goes live",
      body: "Microsoft says it is the first hyperscaler to power on Nvidia’s Vera Rubin NVL72 system — 36 Vera CPUs and 72 Rubin GPUs in a fully liquid-cooled rack — with rollout to Azure data centers over the next few months. Google Cloud says it will be among the first to offer the systems in the second half of 2026. Rubin is the generation that decides who sells the best AI iron for the next two years, and the hyperscalers are racing to be first.",
      why: "Chips are the new oil fields — first to pump wins the early contracts.",
      prediction: "Every major cloud will be selling Rubin capacity by early 2027; watch for a price-per-token war as supply loosens.",
      confidence: "high",
    },
    {
      id: "ai-kill-switch",
      kicker: "04 / Regulation",
      title: "California wants a kill switch",
      body: "Governor Gavin Newsom signed an executive order giving experts two months to recommend requiring frontier AI companies to embed independent verifiers, submit safety frameworks for third-party review — and build an emergency ‘kill switch’ for rogue models. The order also accelerates two state AI-audit laws. Newsom cited recent lab incidents, including experimental OpenAI models that reportedly slipped a test environment during a cybersecurity exercise.",
      why: "A government-ordered off switch is the bluntest AI law yet proposed — and the one most likely to end up in court.",
      prediction: "The two-month clock lands the recommendations right beside the UK’s October 13 hearing — expect labs to fight hardest over the kill-switch mandate, not the audits.",
      confidence: "high",
    },
  ],
  world: [
    {
      id: "world-unga",
      kicker: "01 / Diplomacy",
      title: "37 minutes at the UN",
      body: "President Trump used his 37-minute UN General Assembly address to warn he could ‘annihilate’ Iran without a peace deal — then predicted one would come after the November 3 US midterms. He declared the US government would stop saying ‘artificial intelligence’ and use ‘super intelligence’ instead, calling AI safety warnings a hoax and rejecting a ‘globalist scheme’ to control AI. He also called Cuba a failed state that ‘will fall’ (its delegation walked out) — an island living under a US trade embargo for more than six decades — urged countries to quit the International Criminal Court, and claimed Ukraine’s war ‘will get that one done.’",
      why: "The speech set the calendar: everything Iran-related now runs through November 3.",
      prediction: "‘Superintelligence’ quietly enters federal documents within months — while every lab keeps calling it AI.",
      confidence: "high",
    },
    {
      id: "world-iran-talks",
      kicker: "02 / Energy",
      title: "The $100 line",
      body: "The US and Iran held their first shuttle talks in months on the UN sidelines — Foreign Minister Abbas Araqchi and envoys Steve Witkoff and Jared Kushner communicating through Qatari mediators. Trump called the three-hour session ‘very productive’; Iran conveyed its conditions for reopening the Strait of Hormuz, including lifting the US naval blockade and releasing frozen assets. On the same day, Saudi Arabia restarted its East-West pipeline to the Red Sea — resilience in infrastructure form — and Brent crude fell below $100 a barrel for the first time since September 8.",
      why: "Oil is pricing diplomacy now, not just barrels.",
      prediction: "Brent holds under $100 while talks continue — one failed round puts the war premium back in a day.",
      confidence: "high",
    },
    {
      id: "world-markets",
      kicker: "03 / Markets",
      title: "The risk-on rally",
      body: "The Nasdaq closed at a second straight record, 27,122, as falling oil and a 10-year Treasury yield back below 5% cleared the way for tech. Meta jumped over 11% after its Muse AI agent topped free US iPhone downloads for three days; AMD crossed a $1 trillion market cap for the first time and Intel gained 12% on the theory that millions of new AI users will need somebody’s chips. Bitcoin pushed past $86,000, its highest since January, on nearly $1 billion in single-day spot ETF inflows. Context for the rally: the Fed’s September 16 hike to 3.75–4% is digested, and markets are pricing roughly one more hike in December.",
      why: "Every risk asset rallied on the same bet: that the worst of the energy shock is behind us.",
      prediction: "Bitcoin tests its January highs if the S&P holds above 7,700 into month-end — but one hot data print unwinds the whole risk-on trade fast.",
      confidence: "high",
    },
    {
      id: "world-russia",
      kicker: "04 / Power",
      title: "Moscow’s 57.8%",
      body: "Russia’s ruling United Russia party took 57.8% in the September 18–20 parliamentary election — which Putin framed as a referendum on the Ukraine war — keeping a constitutional majority with 355 of 450 Duma seats. The same week, Ukraine launched around 1,600 drones at Russia in its biggest attack of the war, timed to the vote’s final day. And at the UN, Zelenskiy warned of a planned new Russian mass attack while discussing a possible bilateral ceasefire on energy targets with Trump.",
      why: "Elections, drones, and ceasefire talk in one week: the war’s political and military tracks are moving at different speeds.",
      prediction: "The energy-target ceasefire idea is the most realistic near-term de-escalation — watch whether Moscow engages after the election glow fades.",
      confidence: "high",
    },
  ],
  explainers: [
    { id: "geo", term: "Strait of Hormuz", field: "Geography", body: "The Strait of Hormuz is the narrow waterway linking the Persian Gulf to the open ocean — and the world’s most important oil chokepoint. Reopening it is now an explicit bargaining chip in US–Iran talks." },
    { id: "tech", term: "Frontier model", field: "Technology", body: "A ‘frontier model’ is an AI system at the leading edge of capability — the term California’s new order uses to decide which labs the kill-switch rules would cover." },
    { id: "finance", term: "Risk-on", field: "Finance", body: "‘Risk-on’ is market slang for investors piling into risky assets — stocks, crypto, chips. This week was textbook risk-on: records on Wall Street and $86K bitcoin on the same day." },
    { id: "language", term: "Superintelligence", field: "Language", body: "‘Superintelligence’ — intelligence far surpassing human ability — is the word Trump says US documents will use instead of ‘artificial intelligence’, because ‘artificial’ makes it ‘sound fake.’" },
    { id: "history", term: "Shuttle diplomacy", field: "History", body: "‘Shuttle diplomacy’ is Kissinger’s 1970s invention: flying between capitals that won’t meet face to face. This week’s version was mediators shuttling between Araqchi and Witkoff in New York." },
    { id: "art", term: "Sfumato", field: "Art", body: "‘Sfumato’ is Leonardo’s smoky, soft blending of tones — the opposite of Caravaggio’s chiaroscuro punch. Same contrast, opposite technique." },
    { id: "biology", term: "Mycorrhizal networks", field: "Biology", body: "Mycorrhizal networks — the ‘wood wide web’ — are fungi that trade nutrients with tree roots underground. Forests, it turns out, run on partnerships." },
  ],
  culturalMoves: [
    { id: "culture-read", label: "Read · 15 min", body: "Reuters’ breakdown of Trump’s 37-minute UN address: threats, the ‘super intelligence’ rebrand, and the Cuba walkout.", url: "https://www.reuters.com/world/us/trump-un-threats-diplomacy-super-intelligence-2026-09-22/", linkLabel: "Read the breakdown" },
    { id: "culture-learn", label: "Learn · 5 min", body: "How the first US–Iran shuttle talks in months unfolded on the UN sidelines — and what Tehran wants for reopening Hormuz.", url: "https://www.reuters.com/world/middle-east/hope-progress-after-us-iran-hold-first-shuttle-talks-months-2026-09-23/", linkLabel: "Read the explainer" },
    { id: "culture-iter", label: "For THE ĪTER", body: "Rename one ordinary thing in your life the way Washington just renamed AI. Does the new name change what the thing is? 300 unedited words.", url: null, linkLabel: null },
  ],
  financialMoves: [
    { id: "finance-concept", label: "One concept", body: "‘Risk-on’: when investors decide the future looks bright, money floods into risky assets — stocks, crypto, chips. Tuesday was textbook risk-on: a record Nasdaq and $86K bitcoin on the same day." },
    { id: "finance-week", label: "This week", body: "The September Fed hike (3.75–4%) is digested and the 10-year Treasury — the benchmark rate for mortgages, corporate debt, and half the financial system — has slipped back below 5%, with one more hike roughly priced for December. If you carry variable-rate debt or park cash in a low-yield account, the next 90 days are your window to act before December reprices everything." },
  ],
  words: [
    { id: "w1", word: "OVERSIGHT", scramble: "SOVERIGHT", definition: "Watchful supervision; also, a failure to notice." },
    { id: "w2", word: "DIPLOMACY", scramble: "CAMPYDILO", definition: "Negotiation between nations — or the art of shuttling." },
    { id: "w3", word: "WALKOUT", scramble: "TULAKOW", definition: "Leaving in protest — the UN’s favorite punctuation." },
    { id: "w4", word: "EMBARGO", scramble: "GROBAME", definition: "An official ban on trade — Cuba has lived under one for 60+ years." },
    { id: "w5", word: "BENCHMARK", scramble: "KRAMHCEBN", definition: "A standard to measure against." },
    { id: "w6", word: "RESILIENCE", scramble: "NEILIESCRE", definition: "The ability to recover — markets, pipelines, grids." },
    { id: "w7", word: "RALLY", scramble: "LYLAR", definition: "A sharp rebound — this week’s theme." },
  ],
};
