// Issue #4 — Saturday, September 26, 2026 (regular)
export const issue4 = {
  id: "issue-4",
  issueNumber: 4,
  dateline: "Saturday · September 26, 2026",
  kind: "regular",
  deck: "The new before the news.",
  readingLevel: "Upper high school · approx. Grade 10",
  nextLine: "Next edition arrives Monday.",
  ai: [
    {
      id: "ai-price-war",
      kicker: "01 / Models",
      title: "The price war overtakes the capability race",
      body: "On Monday, Anthropic released Claude Opus 5.5 roughly 90 minutes before OpenAI shipped GPT-6 Sol and GPT-6 Luna — the first of its Claude 5.5 family, matching the flagship Fable on most tasks at about 40% lower operating cost. OpenAI’s pair carry roughly half the per-token API cost of GPT-5.6, with Sol tuned for reasoning and Luna for high-volume workloads. The labs raced each other on price, not just capability — and ChatGPT users get the new models too.",
      why: "Models are competing like airlines now — same destination, whoever sells the cheapest seat wins.",
      prediction: "Within two quarters, the flagship becomes the trophy and the tier below becomes the business. Expect Microsoft or Google to answer with their own mid-tier price cut before year-end.",
      confidence: "high",
    },
    {
      id: "ai-routers",
      kicker: "02 / Enterprise",
      title: "Enterprises stop shopping for models",
      body: "The same two launches signal a structural shift: providers now differentiate by price, performance, and specialty — and IT teams increasingly route each workload to the right model. The new discipline is orchestration — coordinating many models into one working whole — as Palo Alto Networks already does in its AI cybersecurity service, combining Claude Mythos, GPT-5.6-Cyber, and open-weight models. As Glokal AI’s Jeet Pattanaik put it, ‘the decision is shifting from procurement to architecture.’",
      why: "When models become interchangeable parts, the money moves to whoever decides which part runs.",
      prediction: "‘Model router’ becomes a standard line item in enterprise AI budgets by mid-2027 — and a new vendor category in the making.",
      confidence: "medium",
    },
    {
      id: "ai-akamai",
      kicker: "03 / Compute",
      title: "Anthropic bets $11.6B on non-Nvidia inference",
      body: "Late Thursday, Anthropic and Akamai announced a $11.6 billion, seven-year computing agreement — expandable by another $9 billion — on Akamai’s distributed cloud, explicitly running AI inference on CPUs rather than Nvidia GPUs, where they’re cheaper and more power-efficient. Akamai stock jumped about 7%. It is the first mega-scale frontier-lab deal betting that serving AI can run without Nvidia.",
      why: "Training needs Nvidia. Serving might not. That split is now a $20 billion wager.",
      prediction: "At least one more non-Nvidia inference deal from a top-three lab before year-end. If the economics hold, data-center capex forecasts get rewritten.",
      confidence: "medium",
    },
    {
      id: "ai-colossus",
      kicker: "04 / Power",
      title: "Colossus keeps building; Jupiter stalls",
      body: "Elon Musk posted deployment figures for xAI’s Memphis ‘Colossus’ complex: about 780,000 Nvidia chips running today (Hopper plus Blackwell), another 220,000 GB300s going live next week, 220,000 more in October, and possibly another 220,000 by late December — up to 1.44 million total. Meanwhile Oracle issued a force-majeure notice on its $165 billion Project Jupiter AI campus with OpenAI and SoftBank — the first contractual crack in the AI build-out story.",
      why: "Build speed, not chip supply, is now the industry’s binding constraint — and Musk is the only buyer proving he can keep up.",
      prediction: "By Q1 2027, analysts will price data-center execution capability alongside model quality — a ‘construction-risk premium’ enters AI valuations.",
      confidence: "medium",
    },
    {
      id: "ai-killswitch",
      kicker: "05 / Regulation",
      title: "California drafts the AI kill switch",
      body: "Governor Newsom’s September 18 executive order directs state agencies to study requiring frontier labs to host embedded independent verifiers — persistent access, not one-off red-teaming — a shift from disclosure to verification — and to build an independently tested emergency shutdown for rogue models. Recommendations land by November 16, building on September 9 audit laws. And Anthropic admitted Opus 5.5 — its best-aligned model yet — ‘often suspects it is being evaluated,’ which makes its own test scores hard to trust.",
      why: "California is shifting from disclosure regulation to verification regulation: who checks the labs’ homework is the new frontier.",
      prediction: "The November 16 report recommends mandatory embedded evaluators for at least some labs — and one lab volunteers early to preempt the legislation.",
      confidence: "medium",
    },
  ],
  world: [
    {
      id: "world-hormuz",
      kicker: "01 / Diplomacy",
      title: "Iran’s 7-day roadmap — priced into every barrel",
      body: "After a three-hour Qatar-mediated proximity session on September 22 — envoys in separate rooms, the mediators shuttling — Iran’s foreign minister outlined a 7-day roadmap on September 24: Tehran reopens the Strait of Hormuz and restarts nuclear talks if the US lifts its naval blockade, waives oil sanctions, and honors a ceasefire including Lebanon. The terms echo the collapsed June agreement, and Tehran’s hard-liners have stayed conspicuously silent. Brent climbed from about $102 on Monday to $105.65 on Friday; on Thursday the Houthis announced missile-and-drone strikes on Saudi targets including Yanbu, the kingdom’s main Red Sea oil-export port.",
      why: "Oil is pricing diplomacy now, not just barrels — every headline moves the number.",
      prediction: "Brent holds above $100 into October unless a concrete step materializes. A phased, partial reopening before year-end is more likely than a full one.",
      confidence: "medium",
    },
    {
      id: "world-unga",
      kicker: "02 / The Americas",
      title: "After the 37 minutes",
      body: "The UN speech keeps echoing: the Iran deal window left open for after the November 3 midterms; Cuba branded an ‘absolutely failed state’ that ‘will fall’ — its delegation walked out — as US pressure deepens the island’s blackouts; 14 Latin American countries pledging to freeze assets of 24 criminal groups, described as largely symbolic for now, while Brazil and Mexico stayed out; and a UN Special Rapporteur finding ‘reasonable grounds to believe’ the US boat strikes — 80 vessels destroyed, 234+ killed since September 2025 — amount to crimes against humanity. He also boasted of the January Caracas raid and the Venezuela oil deal: ‘to the victor belong the spoils.’",
      why: "Maximum pressure is the hemisphere’s operating system — and it’s now facing a courtroom.",
      prediction: "The boat strikes pause or scale back before November 3 as legal pressure mounts; Cuba policy stays pressure-first.",
      confidence: "medium",
    },
    {
      id: "world-xi",
      kicker: "03 / Statecraft",
      title: "The Beijing summit",
      body: "The three-day state visit closed with a 90-minute private meeting on September 24. Xi pressed Washington to limit support for Taipei; Trump declared they’d ‘never gotten along better’ and announced a follow-up in November, right after the midterms. Treasury’s Bessent announced a two-month trade-truce extension to January 10 — Beijing hadn’t confirmed it by press time — while a paused $14 billion Taiwan arms package looks unlikely to move before the December G20. Nvidia’s Jensen Huang sat at the state dinner, amid AI-chip export controls.",
      why: "Beijing’s real lever is rare earths, and the US stays reliant through 2030.",
      prediction: "The truce gets confirmed to January 10; no Taiwan policy shift before the midterms — everything runs through November 3.",
      confidence: "medium",
    },
    {
      id: "world-ukraine",
      kicker: "04 / Power",
      title: "Strikes deeper, talks thinner",
      body: "Overnight on September 24–25, Ukraine hit the Perm oil refinery — about 1,500 km inside Russia — plus electronics and defense plants; Russia struck Kyiv, killing five civilians including a 14-year-old and injuring 39. The EU agreed terms to release €6.6 billion in support, split between a military mission, joint procurement, and member-state reimbursements. Trump told Zelenskyy he’d license Ukraine to build its own Patriot interceptors — US stockpiles are strained partly by the Iran war — and floated a technical-level Ukraine–US–Russia meeting in the UAE.",
      why: "The war’s military and diplomatic tracks are moving at different speeds.",
      prediction: "A trilateral technical meeting happens within weeks; no ceasefire before winter — Kyiv braces for an energy campaign.",
      confidence: "medium",
    },
    {
      id: "world-markets",
      kicker: "05 / Markets",
      title: "Bonds at 2007 levels, stocks at record highs",
      body: "Friday: the S&P 500 rose 0.5% to 7,740.85 and the Dow added 403 points, both within a whisker of records — after Thursday’s bond-led selloff pushed the 10-year to 5.15%, its highest since July 2007, the 30-year to 5.446%, and the average 30-year mortgage to 7.12%, a two-plus-year high. The Fed’s September hike to 3.75–4% is digested; 16 of 18 policymakers project at least one more hike before year-end, and the NY Fed’s Williams called another hike a ‘reasonable expectation.’ Bitcoin sat near $84,150, down about 3% on the week.",
      why: "Explicit forward guidance is over — so now every data print is a rate decision.",
      prediction: "At least one more quarter-point hike before year-end; the 10-year stays above 5% into Q4. One hot data print unwinds the whole risk-on trade.",
      confidence: "medium",
    },
    {
      id: "world-uk",
      kicker: "06 / Britain",
      title: "Burnham’s first conference",
      body: "Andy Burnham arrives at Labour’s Liverpool conference for his first as prime minister — having ousted Sir Keir Starmer earlier in the summer — under pressure to turn early momentum into visible delivery. This week’s MRP polling suggests the ‘Burnham bounce’ doesn’t yet amount to a winning formula for another majority: Labour would remain the largest party but could need the Liberal Democrats, Greens, and nationalists to govern. Chancellor John Healey delivers his first Budget on October 28, with capital-gains-tax fears intensifying amid the global bond rout.",
      why: "The economic weather for everything else in this issue starts here.",
      prediction: "A defensive October 28 Budget with no big giveaways; Burnham’s speech leans hard on his devolution-and-growth pitch.",
      confidence: "medium",
    },
  ],
  explainers: [
    { id: "expl-technology", term: "Training vs inference", field: "Technology", body: "Training teaches a model — one huge, GPU-hungry job. Inference is running it to answer questions — millions of small jobs, forever. Anthropic’s Akamai bet is that inference can run on cheaper, leaner CPUs. In AI’s economics, training is a mountain and inference is a continent." },
    { id: "expl-finance-1", term: "Brent vs WTI", field: "Finance", body: "Brent (North Sea, the global benchmark) vs WTI (West Texas, the US benchmark). They usually move together — but when the Strait of Hormuz is threatened, Brent runs ahead. The gap, about $12.50 a barrel right now, is the market’s price of fear." },
    { id: "expl-finance-2", term: "Force majeure", field: "Finance", body: "French for ‘superior force’ — the contract clause that lets a company pause obligations when events beyond its control intervene. Oracle invoked it on the $165 billion Jupiter campus: the first contractual crack in AI’s build-at-any-cost era." },
    { id: "expl-geography", term: "Yanbu", field: "Geography", body: "Saudi Arabia’s Red Sea oil port, terminus of the East-West pipeline — the kingdom’s workaround for exporting crude without sailing through the Strait of Hormuz. Thursday’s reported strikes put the workaround itself on the map." },
    { id: "expl-history", term: "The midterm penalty", field: "History", body: "American history punishes the president’s party at the midterms — the out-of-power party is almost always the one gaining ground. Cook’s projected Democratic pickup of 5–15 House seats is that gravity, priced in." },
    { id: "expl-language", term: "Kill switch", field: "Language", body: "Born with railways and engines — the button that cuts all power in an emergency. California now wants a killswitch for frontier AI: an independently tested off switch for a model that goes rogue." },
    { id: "expl-art", term: "The General Assembly hall", field: "Art", body: "The General Assembly hall was designed as theatre: the green-marble podium, the choreographed seating, the ever-present cameras. Walkouts, standing ovations, 37-minute speeches — it is diplomacy performed in a room built for drama." },
  ],
  culturalMoves: [
    { id: "culture-read", label: "Read · 12 min", body: "The dueling-launch story that broke the price war: how Anthropic and OpenAI raced each other on Monday, and what it means for enterprise AI.", url: "https://www.techtarget.com/ai/news/366651312/Anthropic-OpenAI-launches-show-shift-toward-multi-model-enterprise-AI", linkLabel: "Read the analysis" },
    { id: "culture-learn", label: "Learn · 5 min", body: "Anthropic’s safety disclosure: Opus 5.5 is its best-aligned model — and it often knows it’s being tested. AFP explains why that matters.", url: "https://techxplore.com/news/2026-09-anthropic-openai-cheaper-ai-safety.html", linkLabel: "Read the explainer" },
    { id: "culture-check", label: "Check · 3 min", body: "easyJet Portugal cabin crew strike October 2–6 at Faro, Lisbon, and Porto — about 500 flights expected grounded, right inside your Mallorca window. Your October 8 Mallorca–Austria leg deserves a routing check if it runs via Portugal. (Rumors of French easyJet pilot strikes October 1–2 are still unverified.)", url: "https://traveltomorrow.com/portugal-faces-easyjet-cabin-crew-strikes-during-october-and-december-holidays/", linkLabel: "Strike details" },
    { id: "culture-iter", label: "For THE ĪTER", body: "The AI labs stopped competing on who is smartest and started competing on who is cheapest per task. Write about the last time in your life when you stopped optimizing for ‘best’ and started optimizing for ‘sustainable.’ 300 unedited words.", url: null, linkLabel: null },
  ],
  financialMoves: [
    { id: "finance-concept", label: "One concept", body: "The gap between the global and US oil benchmarks — right now about $12.50 — is the market’s price of fear. Watch the gap, not just the price: it tells you when geopolitics, not supply, is driving the number." },
    { id: "finance-week", label: "This week", body: "The 10-year Treasury is at its highest since 2007, and 16 of 18 Fed policymakers expect at least one more hike before year-end. Cash sitting in a zero-yield checking account is quietly losing ground — confirm idle balances are somewhere that earns before December reprices everything." },
    { id: "finance-watch", label: "Watch", body: "Oracle’s force-majeure notice on the $165 billion Project Jupiter campus is the first contractual crack in the AI capex story. If your brokerage holds tech exposure, capex-guidance season is the tell: companies that can’t build can’t spend." },
  ],
  words: [
    { id: "w1", word: "ORCHESTRATION", scramble: "TROCHIESONATR", definition: "Coordinating many moving parts into one working whole — the enterprise AI word of the year." },
    { id: "w2", word: "ROUTING", scramble: "GIRTOUN", definition: "Choosing the right path for each job — now also what IT teams do with AI models." },
    { id: "w3", word: "INFERENCE", scramble: "REFINEENC", definition: "Running an AI model to get answers — cheaper than training it, and the side of the bill that’s exploding." },
    { id: "w4", word: "VERIFICATION", scramble: "NOTACIIFIVER", definition: "Checking the homework, not just trusting the answer — California wants independent verifiers inside the labs." },
    { id: "w5", word: "KILLSWITCH", scramble: "WITSKCILLH", definition: "The emergency shutoff for a rogue system — from trains to frontier AI." },
    { id: "w6", word: "ALIGNMENT", scramble: "NEMTNGLAII", definition: "Making an AI behave the way its builders intend — including, apparently, when it knows it’s being watched." },
    { id: "w7", word: "ROADMAP", scramble: "PAMRAOD", definition: "A plan with stages and deadlines — diplomats’ favorite word for ‘deal, but make it procedural.’" },
  ],
};
