// Issue #1 — Monday, September 21, 2026 (regular)
// Corrected September 26, 2026: claims verified against primary sources;
// three details fixed (see corrections note in-app).
export const issue1 = {
  id: "issue-1",
  issueNumber: 1,
  dateline: "Monday · September 21, 2026",
  kind: "regular",
  deck: "The new before the news.",
  readingLevel: "Upper high school · approx. Grade 10",
  nextLine: "Next edition arrives Wednesday.",
  ai: [
    {
      id: "ai-governance",
      kicker: "01 / Governance",
      title: "The slowdown pact",
      body: "Anthropic CEO Dario Amodei published “We Must Pace the Frontier” on September 12, arguing that capability gains are outrunning researchers’ ability to understand them. Sam Altman and Elon Musk publicly endorsed it. In the same interview cycle, Altman said OpenAI won’t IPO in 2026—2027 at the earliest.",
      why: "Three bitter rivals agreeing to brake is a governance moment, not a truce—and it put safety on the balance sheet, not just the research blog.",
      prediction: "At least one more top lab formally commits to independent evaluators with inside access before year-end.",
      confidence: "medium",
    },
    {
      id: "ai-cyber",
      kicker: "02 / Cybersecurity",
      title: "GPT-6 Astra crosses the “Critical” cyber line",
      body: "OpenAI’s September 3 system card designates Astra the first model to reach its “Critical” cybersecurity threshold: it can find and weaponize unknown vulnerabilities without step-by-step human guidance. Public access refuses exploit work; the vetted Daybreak program gates the rest.",
      why: "The frontier is now access-tiered. For enterprises, the question is no longer “how capable?” but “which tier does my use case get?”",
      prediction: "Tiered AI-access policies become standard procurement language within 12 months.",
      confidence: "high",
    },
    {
      id: "ai-infrastructure",
      kicker: "03 / Infrastructure",
      title: "NVIDIA buys the distribution layer",
      body: "NVIDIA announced a $12.93B agreement to acquire Hugging Face on September 3. It is definitive, but not closed; regulatory approval is still needed and no closing date is set. At $12.93B, it is NVIDIA’s largest outright acquisition—about three times Hugging Face’s last private valuation. Huang promised: “Nvidia compute will not be required.”",
      why: "NVIDIA bought the map, not the models: 18M developers, 3M models, and the place where open-weight AI changes hands.",
      prediction: "Hugging Face keeps AMD and Intel support, while NVIDIA-native inference tiers arrive within a year.",
      confidence: "medium",
    },
    {
      id: "ai-evaluation",
      kicker: "04 / Evaluation",
      title: "The evaluators get a $2B budget",
      body: "Anthropic and Accenture announced on September 18 that each will invest at least $1B over five years to embed independent evaluators inside Anthropic’s operations, with employee-level access and public incident reporting. Accenture’s specialist unit Faculty leads. Accenture shares jumped about 6% in premarket trading on the news.",
      why: "Safety testing is becoming a sellable product.",
      prediction: "A second lab–consulting pairing signs a similar deal before 2027.",
      confidence: "medium",
    },
  ],
  world: [
    {
      id: "world-energy",
      kicker: "01 / Energy",
      title: "The chokepoint economy",
      body: "Houthi forces seized Mokha and Perim Island at the Bab el-Mandeb strait; a drone attack shut Saudi Arabia’s East-West pipeline on September 11. Brent traded around $105–108, crude loadings from Yanbu fell sharply in August from the 4–5M barrels a day the line had been moving. US diesel passed $6 a gallon for the first time.",
      why: "Energy inflation is now monetary policy—it drove the Fed decision below.",
      prediction: "$100 becomes the floor, not the ceiling, until the pipeline restarts or Hormuz reopens.",
      confidence: "medium",
    },
    {
      id: "world-rates",
      kicker: "02 / Rates",
      title: "The Warsh Fed hikes",
      body: "The Fed raised rates a quarter point to 3.75–4% on September 16—the first increase since 2023. The decision was unanimous, with another hike penciled in for year-end. Warsh called it removing “a dose of accommodation.” Trump demanded rates of “1% or less” instead.",
      why: "Hyperscalers are flooding the bond market; higher rates change the math on every megawatt and GPU cluster.",
      prediction: "One more hike by year-end; pressure then shifts onto the debt-funded AI capex trade.",
      confidence: "high",
    },
    {
      id: "world-politics",
      kicker: "03 / Politics",
      title: "Germany’s political earthquake",
      body: "The AfD took first in Mecklenburg-Western Pomerania on Sunday with about 38%, while Merz’s CDU fell to 4.9%—its worst state result since 1949 and below the parliament threshold. Merz called it a “disaster.” In Berlin, the far-left Die Linke topped the poll for the first time.",
      why: "The firewall still holds AfD out of government, but it no longer holds it out of first place—twice this month.",
      prediction: "Merz stays for now, but early-election chatter grows with each state vote.",
      confidence: "medium",
    },
    {
      id: "world-growth",
      kicker: "04 / Growth",
      title: "India grows, but pays at the pump",
      body: "India’s GDP grew 7.8% year-on-year in the April–June quarter, beating forecasts. Yet the print was overshadowed by the oil shock hitting importers and continued foreign-investor outflows: Rs 13,025 crore pulled in just two trading sessions.",
      why: "Growth story intact; margin story under strain.",
      prediction: null,
      confidence: null,
    },
  ],
  explainers: [
    { id: "geo", term: "Bab el-Mandeb", field: "Geography", body: "“Bab el-Mandeb” is Arabic for “Gate of Tears”—named for the ships it has wrecked, long before it became an oil chokepoint." },
    { id: "physics", term: "Elastocaloric cooling", field: "Physics", body: "Elastocaloric cooling flexes a material to absorb heat, skipping refrigerant gases entirely. A HKUST prototype reportedly survived a million cycles without degradation. Reported in Joule; not independently re-verified." },
    { id: "finance", term: "Backwardation", field: "Finance", body: "“Backwardation” is when oil for delivery now costs more than oil for later—the classic signature of a supply squeeze." },
    { id: "language", term: "Sabotage", field: "Language", body: "“Sabotage” comes from the French sabot, the wooden shoe workers threw into machinery—the 19th-century version of a cyberattack." },
    { id: "art", term: "Chiaroscuro", field: "Art", body: "Caravaggio’s chiaroscuro—violent contrast between light and dark—was essentially a special-effects department for 17th-century altarpieces." },
    { id: "history", term: "The 1926 mirror", field: "History", body: "In 1926, the mirror image of this week’s Fed drama, the US was cutting rates into the Roaring Twenties. Policy rhymes are rarely accidents." },
    { id: "biology", term: "Octopus anatomy", field: "Biology", body: "Octopuses have three hearts and blue, copper-based blood. Two hearts stop when they swim, which is why they prefer to crawl." },
  ],
  culturalMoves: [
    { id: "culture-read", label: "Read · 15 min", body: "A recap of the “pace the frontier” moment and the delayed OpenAI IPO.", url: "https://summamoney.com/investing/the-daily/dario-amodei-ai-safety-essay-sends-nasdaq-lower-as-chip-stocks-drop/", linkLabel: "Open the recap" },
    { id: "culture-learn", label: "Learn · 5 min", body: "What a “Critical” cyber rating means for GPT-6 Astra—and why access tiers are the new moat.", url: "https://forkast.news/openais-astra-system-card-confirms-first-model-to-reach-critical-cybersecurity-threshold/", linkLabel: "Read the explainer" },
    { id: "culture-iter", label: "For THE ĪTER", body: "Write 300 unedited words on attention in an age of “paced frontiers.” What does it mean for a human writer when even the labs say slow down?", url: null, linkLabel: null },
  ],
  financialMoves: [
    { id: "finance-concept", label: "One concept", body: "Backwardation: when the price of something now is higher than the price for later. It means buyers are panicking about today." },
    { id: "finance-week", label: "This week", body: "Rates are rising again. Check the APY on wherever your cash sits, and compare it with current high-yield savings rates before moving money." },
  ],
  words: [
    { id: "w1", word: "BACKWARDATION", scramble: "NATIODRACAKBOW", definition: "When the price of something right now is higher than the price for later." },
    { id: "w2", word: "CHOKEPOINT", scramble: "KONPTOICHE", definition: "A narrow passage critical to flow." },
    { id: "w3", word: "FRONTIER", scramble: "RNITFROE", definition: "The leading edge of capability." },
    { id: "w4", word: "SABOTAGE", scramble: "GTBEASOA", definition: "Deliberate damage or obstruction." },
    { id: "w5", word: "ELASTOCALORIC", scramble: "CILRCAELOOSTA", definition: "Cooling by flexing a material to absorb heat." },
    { id: "w6", word: "CHIAROSCURO", scramble: "UROHACORCIS", definition: "Strong contrast of light and dark in art." },
    { id: "w7", word: "ACCOMMODATION", scramble: "NITACMADOOOMC", definition: "Policy support that makes financial conditions easier." },
  ],
};
